"""Create users table

Revision ID: 53e7e47890a8
Revises: 600d59f2e604
Create Date: 2024-11-12 13:37:59.018629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e7e47890a8'
down_revision: Union[str, None] = '600d59f2e604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_reset_token', table_name='users')
    op.drop_index('ix_users_token', table_name='users')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_users_token', 'users', ['token'], unique=True)
    op.create_index('ix_users_reset_token', 'users', ['reset_token'], unique=True)
    # ### end Alembic commands ###
