"""initial migration

Revision ID: 6489b6153639
Revises: e074ee4b66f3
Create Date: 2024-12-10 06:58:39.372770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6489b6153639'
down_revision: Union[str, None] = 'e074ee4b66f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('photo', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.alter_column('catalogs', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalogs', 'information',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('catalogs', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalogs', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('catalogs', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('catalogs', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('catalogs', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalogs', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('catalogs', 'information',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('catalogs', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_table('favorites')
    # ### end Alembic commands ###
