"""Миграцияның сипаттамасы

Revision ID: 7846e5c57da6
Revises: ae2791feb6c5
Create Date: 2024-12-09 11:07:39.735180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7846e5c57da6'
down_revision: Union[str, None] = 'ae2791feb6c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_favorites_id', table_name='favorites')
    op.drop_table('favorites')
    op.add_column('catalogs', sa.Column('information', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('catalogs', 'description3')
    op.drop_column('catalogs', 'description2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogs', sa.Column('description2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('catalogs', sa.Column('description3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('catalogs', 'information')
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('catalog_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalogs.id'], name='favorites_catalog_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey')
    )
    op.create_index('ix_favorites_id', 'favorites', ['id'], unique=False)
    # ### end Alembic commands ###
