"""Миграцияның сипаттамасы

Revision ID: e074ee4b66f3
Revises: 7846e5c57da6
Create Date: 2024-12-09 11:16:43.889337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e074ee4b66f3'
down_revision: Union[str, None] = '7846e5c57da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
